name: Webapp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: webapp

env:
  CARGO_TERM_COLOR: always

jobs:
  build_wasm_package:
    name: Build wasm package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: Build wasm package
        run: wasm-pack build
      - name: Upload wasm package
        uses: actions/upload-artifact@v2
        with:
          name: rusty-pedestrians-engine
          path: engine/pkg/
  build:
    name: Build webapp
    runs-on: ubuntu-latest
    needs: build_wasm_package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Download wasm-package
        uses: actions/download-artifact@v2
        with:
          name: rusty-pedestrians-engine
          path: engine/pkg/
      - name: Install dependencies
        run: npm install
      - name: Build webapp
        run: npm run build
      - name: Upload webapp
        uses: actions/upload-artifact@v2
        with:
          name: rusty-pedestrians-webapp
          path: webapp/build
  deploy:
    name: Deploy webapp
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download webapp
        uses: actions/download-artifact@v2
        with:
          name: rusty-pedestrians-webapp
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
